import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, Bug, Lightbulb, MessageSquare, Send, Star } from "lucide-react";
import { useEffect, useState } from "react";
import { useAuth } from "@/hooks/useAuth";
import { sendFeedback } from "@/lib/phase4b";

export const Route = createFileRoute("/feedback")({ ssr: false, head: () => ({ meta: [
  { title: "Feedback · Eklavya" }, { name: "description", content: "Share feedback, suggestions or bug reports with the Eklavya team." }, { property: "og:title", content: "Feedback · Eklavya" }, { property: "og:description", content: "Help improve Eklavya for every student." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
] }), component: FeedbackPage });

function FeedbackPage() {
  const navigate = useNavigate(); const { user, loading } = useAuth(); const [category, setCategory] = useState<"suggestion" | "bug" | "feedback">("feedback"); const [rating, setRating] = useState(5); const [message, setMessage] = useState(""); const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!loading && !user) navigate({ to: "/auth", search: { next: "/feedback" } }); }, [loading, user, navigate]);
  if (loading || !user) return <div className="flex min-h-screen items-center justify-center bg-background text-sm text-muted-foreground">Loading…</div>;
  async function submit(e: React.FormEvent) { e.preventDefault(); if (!message.trim()) return setError("Write a message before sending."); setBusy(true); setError(""); try { await sendFeedback(user.id, { category, rating, message }); setSent(true); setMessage(""); } catch { setError("Could not send feedback. Please try again."); } finally { setBusy(false); } }
  return <div className="min-h-screen bg-background pb-16 text-foreground"><div className="mx-auto max-w-md"><header className="flex items-center justify-between px-5 pt-6 pb-4"><Link to="/settings" className="flex h-10 w-10 items-center justify-center rounded-2xl border border-border bg-card" aria-label="Back"><ArrowLeft className="h-5 w-5" /></Link><h1 className="font-display text-base font-bold">App feedback</h1><div className="w-10" /></header><main className="px-5"><form onSubmit={submit} className="space-y-5"><div><p className="mb-3 text-[11px] font-bold tracking-wider text-muted-foreground uppercase">What would you like to share?</p><div className="grid grid-cols-3 gap-2">{(["feedback", "suggestion", "bug"] as const).map((item) => { const Icon = item === "bug" ? Bug : item === "suggestion" ? Lightbulb : MessageSquare; return <button key={item} type="button" onClick={() => setCategory(item)} className={`flex flex-col items-center gap-2 rounded-2xl border p-3 text-xs font-semibold capitalize ${category === item ? "border-primary bg-primary/10 text-primary" : "border-border bg-card text-muted-foreground"}`}><Icon className="h-5 w-5" />{item}</button>; })}</div></div><div><p className="mb-2 text-[11px] font-bold tracking-wider text-muted-foreground uppercase">Rate your experience</p><div className="flex gap-2">{[1, 2, 3, 4, 5].map((value) => <button key={value} type="button" aria-label={`${value} stars`} onClick={() => setRating(value)}><Star className={`h-7 w-7 ${value <= rating ? "fill-gold text-gold" : "text-muted-foreground"}`} /></button>)}</div></div><label className="block"><span className="text-[11px] font-bold tracking-wider text-muted-foreground uppercase">Your message</span><textarea required maxLength={4000} rows={6} value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Tell us what would make Eklavya better…" className="mt-2 w-full resize-none rounded-2xl border border-border bg-card px-4 py-3 text-sm outline-none focus:border-primary" /></label>{error && <p className="text-xs text-destructive" role="alert">{error}</p>}{sent && <p className="text-xs text-success" role="status">Thanks — your message was sent to the Eklavya team.</p>}<button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-primary px-4 py-3 text-sm font-bold text-primary-foreground"><Send className="h-4 w-4" />{busy ? "Sending…" : "Send suggestion"}</button></form></main></div></div>;
}