import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, Check, Crown, Gift, Lock, Sparkles } from "lucide-react";
import { useEffect } from "react";
import { useAuth, useProfile } from "@/hooks/useAuth";

export const Route = createFileRoute("/premium")({ ssr: false, head: () => ({ meta: [
  { title: "Premium · Eklavya" }, { name: "description", content: "Unlock lifetime premium Eklavya study resources through verified referrals." }, { property: "og:title", content: "Premium · Eklavya" }, { property: "og:description", content: "Unlock lifetime Eklavya Premium." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
] }), component: PremiumPage });

function PremiumPage() { const navigate = useNavigate(); const { user, loading } = useAuth(); const { profile } = useProfile(user); useEffect(() => { if (!loading && !user) navigate({ to: "/auth", search: { next: "/premium" } }); }, [loading, user, navigate]); if (loading || !user) return <div className="flex min-h-screen items-center justify-center bg-background text-sm text-muted-foreground">Loading…</div>; const unlocked = Boolean(profile?.is_premium); return <div className="min-h-screen bg-background pb-16 text-foreground"><div className="mx-auto max-w-md"><header className="flex items-center justify-between px-5 pt-6 pb-4"><Link to="/" className="flex h-10 w-10 items-center justify-center rounded-2xl border border-border bg-card" aria-label="Back"><ArrowLeft className="h-5 w-5" /></Link><h1 className="font-display text-base font-bold">Eklavya Premium</h1><div className="w-10" /></header><main className="space-y-5 px-5"><section className="bg-hero relative overflow-hidden rounded-3xl border border-white/5 p-6 text-center shadow-card-premium"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-gold shadow-gold"><Crown className="h-8 w-8 text-gold-foreground" /></div><h2 className="font-display mt-4 text-2xl font-bold">{unlocked ? "Premium Member" : "Unlock lifetime access"}</h2><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{unlocked ? "Your premium resources are ready whenever you are." : "Invite 10 verified classmates to unlock every premium resource."}</p></section><div className="space-y-2">{["Premium handwritten notes", "Subject-wise formula sheets", "Future premium content", "A focused, ad-free study experience"].map((item) => <div key={item} className="flex items-center gap-3 rounded-2xl border border-border bg-card p-4"><div className="flex h-8 w-8 items-center justify-center rounded-xl bg-success/15"><Check className="h-4 w-4 text-success" /></div><span className="text-sm font-semibold">{item}</span></div>)}</div>{unlocked ? <div className="rounded-2xl border border-success/30 bg-success/10 p-4"><div className="flex items-center gap-3"><Sparkles className="h-5 w-5 text-success" /><div><p className="font-display text-sm font-bold">Lifetime Premium unlocked</p><p className="text-xs text-muted-foreground">Thank you for growing the Eklavya community.</p></div></div></div> : <Link to="/referral" className="flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-primary px-4 py-3 text-sm font-bold text-primary-foreground"><Gift className="h-4 w-4" /> Refer classmates to unlock</Link>} {!unlocked && <div className="flex items-center justify-center gap-2 text-[11px] text-muted-foreground"><Lock className="h-3 w-3" /> Premium content stays protected until unlocked.</div>}</main></div></div>; }