import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, ChevronRight, CircleHelp, Info, MessageSquare, Settings2, Share2, UserRound } from "lucide-react";
import { useEffect } from "react";
import { useAuth } from "@/hooks/useAuth";

export const Route = createFileRoute("/settings")({ ssr: false, head: () => ({ meta: [
  { title: "Settings · Eklavya" }, { name: "description", content: "Manage your Eklavya account, referrals, notifications and support." }, { property: "og:title", content: "Settings · Eklavya" }, { property: "og:description", content: "Manage your Eklavya account and preferences." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
] }), component: SettingsPage });

function SettingsPage() { const navigate = useNavigate(); const { user, loading } = useAuth(); useEffect(() => { if (!loading && !user) navigate({ to: "/auth", search: { next: "/settings" } }); }, [loading, user, navigate]); if (loading || !user) return <div className="flex min-h-screen items-center justify-center bg-background text-sm text-muted-foreground">Loading…</div>; return <div className="min-h-screen bg-background pb-16 text-foreground"><div className="mx-auto max-w-md"><header className="flex items-center justify-between px-5 pt-6 pb-4"><Link to="/profile" className="flex h-10 w-10 items-center justify-center rounded-2xl border border-border bg-card" aria-label="Back"><ArrowLeft className="h-5 w-5" /></Link><h1 className="font-display text-base font-bold">Settings</h1><div className="w-10" /></header><main className="space-y-5 px-5"><section><p className="mb-3 text-[11px] font-bold tracking-wider text-muted-foreground uppercase">Account & growth</p><div className="space-y-2"><SettingLink to="/referral" icon={Share2} title="Refer & Earn" detail="Invite classmates for lifetime Premium" /><SettingLink to="/notifications" icon={Settings2} title="Notifications" detail="Choose your study reminders" /><SettingLink to="/profile" icon={UserRound} title="Profile" detail="Your account and progress" /></div></section><section><p className="mb-3 text-[11px] font-bold tracking-wider text-muted-foreground uppercase">Help & information</p><div className="space-y-2"><SettingLink to="/feedback" icon={MessageSquare} title="App feedback" detail="Suggest an improvement or report a bug" /><SettingLink to="/contact" icon={CircleHelp} title="Contact developer" detail="Get in touch with Raj Veer Chaudhary" /><SettingLink to="/about" icon={Info} title="About app" detail="Version, policies and open source libraries" /></div></section></main></div></div>; }
function SettingLink({ to, icon: Icon, title, detail }: { to: "/referral" | "/notifications" | "/profile" | "/feedback" | "/contact" | "/about"; icon: typeof Share2; title: string; detail: string }) { return <Link to={to} className="flex items-center gap-3 rounded-2xl border border-border bg-card p-4 transition hover:border-primary/50"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10"><Icon className="h-5 w-5 text-primary" /></div><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{title}</p><p className="text-[11px] text-muted-foreground">{detail}</p></div><ChevronRight className="h-4 w-4 text-muted-foreground" /></Link>; }