/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as MockTestRouteImport } from './routes/mock-test'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PracticeSubjectRouteImport } from './routes/practice.$subject'
import { Route as MockTestSubjectRouteImport } from './routes/mock-test.$subject'
import { Route as AdminSubjectsRouteImport } from './routes/admin.subjects'
import { Route as AdminSubSubjectsRouteImport } from './routes/admin.sub-subjects'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminNotesRouteImport } from './routes/admin.notes'
import { Route as AdminMockTestsRouteImport } from './routes/admin.mock-tests'
import { Route as AdminChaptersRouteImport } from './routes/admin.chapters'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as PracticeSubjectSubsubjectRouteImport } from './routes/practice.$subject.$subsubject'
import { Route as PracticeSubjectChapterRouteImport } from './routes/practice.$subject.$chapter'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as PracticeSubjectChapterSetRouteImport } from './routes/practice.$subject.$chapter.$set'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestRoute = MockTestRouteImport.update({
  id: '/mock-test',
  path: '/mock-test',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PracticeSubjectRoute = PracticeSubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => PracticeRoute,
} as any)
const MockTestSubjectRoute = MockTestSubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => MockTestRoute,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubSubjectsRoute = AdminSubSubjectsRouteImport.update({
  id: '/sub-subjects',
  path: '/sub-subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotesRoute = AdminNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMockTestsRoute = AdminMockTestsRouteImport.update({
  id: '/mock-tests',
  path: '/mock-tests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChaptersRoute = AdminChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeSubjectSubsubjectRoute =
  PracticeSubjectSubsubjectRouteImport.update({
    id: '/$subsubject',
    path: '/$subsubject',
    getParentRoute: () => PracticeSubjectRoute,
  } as any)
const PracticeSubjectChapterRoute = PracticeSubjectChapterRouteImport.update({
  id: '/$chapter',
  path: '/$chapter',
  getParentRoute: () => PracticeSubjectRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeSubjectChapterSetRoute =
  PracticeSubjectChapterSetRouteImport.update({
    id: '/$set',
    path: '/$set',
    getParentRoute: () => PracticeSubjectChapterRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/mistakes': typeof MistakesRoute
  '/mock-test': typeof MockTestRouteWithChildren
  '/practice': typeof PracticeRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/chapters': typeof AdminChaptersRoute
  '/admin/mock-tests': typeof AdminMockTestsRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/sub-subjects': typeof AdminSubSubjectsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/mock-test/$subject': typeof MockTestSubjectRoute
  '/practice/$subject': typeof PracticeSubjectRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/practice/$subject/$chapter': typeof PracticeSubjectChapterRouteWithChildren
  '/practice/$subject/$subsubject': typeof PracticeSubjectSubsubjectRoute
  '/practice/$subject/$chapter/$set': typeof PracticeSubjectChapterSetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/mistakes': typeof MistakesRoute
  '/mock-test': typeof MockTestRouteWithChildren
  '/practice': typeof PracticeRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/chapters': typeof AdminChaptersRoute
  '/admin/mock-tests': typeof AdminMockTestsRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/sub-subjects': typeof AdminSubSubjectsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/mock-test/$subject': typeof MockTestSubjectRoute
  '/practice/$subject': typeof PracticeSubjectRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/practice/$subject/$chapter': typeof PracticeSubjectChapterRouteWithChildren
  '/practice/$subject/$subsubject': typeof PracticeSubjectSubsubjectRoute
  '/practice/$subject/$chapter/$set': typeof PracticeSubjectChapterSetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/mistakes': typeof MistakesRoute
  '/mock-test': typeof MockTestRouteWithChildren
  '/practice': typeof PracticeRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/chapters': typeof AdminChaptersRoute
  '/admin/mock-tests': typeof AdminMockTestsRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/sub-subjects': typeof AdminSubSubjectsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/mock-test/$subject': typeof MockTestSubjectRoute
  '/practice/$subject': typeof PracticeSubjectRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/practice/$subject/$chapter': typeof PracticeSubjectChapterRouteWithChildren
  '/practice/$subject/$subsubject': typeof PracticeSubjectSubsubjectRoute
  '/practice/$subject/$chapter/$set': typeof PracticeSubjectChapterSetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/bookmarks'
    | '/forgot-password'
    | '/mcp'
    | '/mistakes'
    | '/mock-test'
    | '/practice'
    | '/profile'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/analytics'
    | '/admin/chapters'
    | '/admin/mock-tests'
    | '/admin/notes'
    | '/admin/notifications'
    | '/admin/questions'
    | '/admin/sub-subjects'
    | '/admin/subjects'
    | '/mock-test/$subject'
    | '/practice/$subject'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/practice/$subject/$chapter'
    | '/practice/$subject/$subsubject'
    | '/practice/$subject/$chapter/$set'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookmarks'
    | '/forgot-password'
    | '/mcp'
    | '/mistakes'
    | '/mock-test'
    | '/practice'
    | '/profile'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/analytics'
    | '/admin/chapters'
    | '/admin/mock-tests'
    | '/admin/notes'
    | '/admin/notifications'
    | '/admin/questions'
    | '/admin/sub-subjects'
    | '/admin/subjects'
    | '/mock-test/$subject'
    | '/practice/$subject'
    | '/admin'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/practice/$subject/$chapter'
    | '/practice/$subject/$subsubject'
    | '/practice/$subject/$chapter/$set'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/bookmarks'
    | '/forgot-password'
    | '/mcp'
    | '/mistakes'
    | '/mock-test'
    | '/practice'
    | '/profile'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/analytics'
    | '/admin/chapters'
    | '/admin/mock-tests'
    | '/admin/notes'
    | '/admin/notifications'
    | '/admin/questions'
    | '/admin/sub-subjects'
    | '/admin/subjects'
    | '/mock-test/$subject'
    | '/practice/$subject'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/practice/$subject/$chapter'
    | '/practice/$subject/$subsubject'
    | '/practice/$subject/$chapter/$set'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookmarksRoute: typeof BookmarksRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  McpRoute: typeof McpRoute
  MistakesRoute: typeof MistakesRoute
  MockTestRoute: typeof MockTestRouteWithChildren
  PracticeRoute: typeof PracticeRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-test': {
      id: '/mock-test'
      path: '/mock-test'
      fullPath: '/mock-test'
      preLoaderRoute: typeof MockTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/practice/$subject': {
      id: '/practice/$subject'
      path: '/$subject'
      fullPath: '/practice/$subject'
      preLoaderRoute: typeof PracticeSubjectRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/mock-test/$subject': {
      id: '/mock-test/$subject'
      path: '/$subject'
      fullPath: '/mock-test/$subject'
      preLoaderRoute: typeof MockTestSubjectRouteImport
      parentRoute: typeof MockTestRoute
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sub-subjects': {
      id: '/admin/sub-subjects'
      path: '/sub-subjects'
      fullPath: '/admin/sub-subjects'
      preLoaderRoute: typeof AdminSubSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notes': {
      id: '/admin/notes'
      path: '/notes'
      fullPath: '/admin/notes'
      preLoaderRoute: typeof AdminNotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mock-tests': {
      id: '/admin/mock-tests'
      path: '/mock-tests'
      fullPath: '/admin/mock-tests'
      preLoaderRoute: typeof AdminMockTestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chapters': {
      id: '/admin/chapters'
      path: '/chapters'
      fullPath: '/admin/chapters'
      preLoaderRoute: typeof AdminChaptersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$subject/$subsubject': {
      id: '/practice/$subject/$subsubject'
      path: '/$subsubject'
      fullPath: '/practice/$subject/$subsubject'
      preLoaderRoute: typeof PracticeSubjectSubsubjectRouteImport
      parentRoute: typeof PracticeSubjectRoute
    }
    '/practice/$subject/$chapter': {
      id: '/practice/$subject/$chapter'
      path: '/$chapter'
      fullPath: '/practice/$subject/$chapter'
      preLoaderRoute: typeof PracticeSubjectChapterRouteImport
      parentRoute: typeof PracticeSubjectRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$subject/$chapter/$set': {
      id: '/practice/$subject/$chapter/$set'
      path: '/$set'
      fullPath: '/practice/$subject/$chapter/$set'
      preLoaderRoute: typeof PracticeSubjectChapterSetRouteImport
      parentRoute: typeof PracticeSubjectChapterRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminChaptersRoute: typeof AdminChaptersRoute
  AdminMockTestsRoute: typeof AdminMockTestsRoute
  AdminNotesRoute: typeof AdminNotesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminSubSubjectsRoute: typeof AdminSubSubjectsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminChaptersRoute: AdminChaptersRoute,
  AdminMockTestsRoute: AdminMockTestsRoute,
  AdminNotesRoute: AdminNotesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminSubSubjectsRoute: AdminSubSubjectsRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MockTestRouteChildren {
  MockTestSubjectRoute: typeof MockTestSubjectRoute
}

const MockTestRouteChildren: MockTestRouteChildren = {
  MockTestSubjectRoute: MockTestSubjectRoute,
}

const MockTestRouteWithChildren = MockTestRoute._addFileChildren(
  MockTestRouteChildren,
)

interface PracticeSubjectChapterRouteChildren {
  PracticeSubjectChapterSetRoute: typeof PracticeSubjectChapterSetRoute
}

const PracticeSubjectChapterRouteChildren: PracticeSubjectChapterRouteChildren =
  {
    PracticeSubjectChapterSetRoute: PracticeSubjectChapterSetRoute,
  }

const PracticeSubjectChapterRouteWithChildren =
  PracticeSubjectChapterRoute._addFileChildren(
    PracticeSubjectChapterRouteChildren,
  )

interface PracticeSubjectRouteChildren {
  PracticeSubjectChapterRoute: typeof PracticeSubjectChapterRouteWithChildren
  PracticeSubjectSubsubjectRoute: typeof PracticeSubjectSubsubjectRoute
}

const PracticeSubjectRouteChildren: PracticeSubjectRouteChildren = {
  PracticeSubjectChapterRoute: PracticeSubjectChapterRouteWithChildren,
  PracticeSubjectSubsubjectRoute: PracticeSubjectSubsubjectRoute,
}

const PracticeSubjectRouteWithChildren = PracticeSubjectRoute._addFileChildren(
  PracticeSubjectRouteChildren,
)

interface PracticeRouteChildren {
  PracticeSubjectRoute: typeof PracticeSubjectRouteWithChildren
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeSubjectRoute: PracticeSubjectRouteWithChildren,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BookmarksRoute: BookmarksRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  McpRoute: McpRoute,
  MistakesRoute: MistakesRoute,
  MockTestRoute: MockTestRouteWithChildren,
  PracticeRoute: PracticeRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
